version: "3.5"

services:
  db:
    container_name: inventory-postgres-container
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tempPassword1
      POSTGRES_DB: inventory
    volumes:
      - "inventory-db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - inventory
    restart: unless-stopped

  pgadmin:
    container_name: inventory-pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@inventory.com
      PGADMIN_DEFAULT_PASSWORD: tempPassword1
    volumes:
      - inventory-pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - inventory
    restart: unless-stopped

networks:
  inventory:
    driver: bridge

volumes:
  inventory-db:
  inventory-pgadmin:
